### ISSUE TITLE
Report of sales

### ISSUE THREAD

**Issue by nsidev** [eventespresso/ee-code-snippet-library#10]
How do I get a report of sales so I can ensure the user gets what they ordered? I will need a report or something to show the buyers name, contact info, shirt size, and quantities at a minimum.

**Comment by mnelson4** [comment]
Hi @nsidev, thanks for posting your question!
This sounds more like a support request which would be better handled by posting it to the Event Espresso support forums: https://eventespresso.com/support/forums/ (that's actually our policy anyways- we use github for development questions, not support)

**Comment by nsidev** [comment]
Interesting. Maybe you can answer this then, where do you store your data? I can write my own reports if i know the table and fields used to store the shirt size.

**Comment by tn3rb** [comment]
or table schemas are declared in: `core/data_migration_scripts/EE_DMS_Core_4_9_0.dms.php`

**Comment by joshfeck** [comment]
If you're capturing the shirt size from a registration form question, your data for that is stored in the _esp_answer table.
