### ISSUE TITLE
Unique PayPal ID - verification of success?

### ISSUE THREAD

**Issue by mfenwick13** [eventespresso/ee-code-snippet-library#2]
When I put in the PayPal ID for an event, I seems to only place the email/ID at the top of the left column on the PayPal screen.  Is there a quick way to see if it is the actual PayPal account?  When we used the default PayPal id, it pulls up the name of our company and not just the email for the account.

**Comment by joshfeck** [comment]
If you input the alternative PayPal ID in Event Espresso > Payment Method settings (ie make it the default for a moment), do a test registration, then click through to PayPal does the company name display on the PayPal screen?

**Comment by mfenwick13** [comment]
Nevermind, all the id emails I had that were "valid" weren't.  I put a fake one into the payment method and the valid one as a paypal_id and it worked by pulling up the name of our company.
