### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by dorian2727** [eventespresso/ee-code-snippet-library#3]
Is this for EE4?

Do you happen to have a list of other values?

**Comment by mnelson4** [comment]
Yes I'm pretty sure all these code snippets are for ee4. I'm not sure what you mean by "a list of other values" though

**Comment by dorian2727** [comment]
What is I wanted to add phone, etc...

**Comment by joshfeck** [comment]
> What is I wanted to add phone, etc...

May I ask, what do you mean? Add phone to what?

**Comment by dorian2727** [comment]
Right now it exports name and email....need to export other values as well..phone number being one of them.

**Comment by mnelson4** [comment]
What export are you referring to? 
Are you referring to the Event Espresso registrations CSV report? I includes the registrations' phone numbers if that question is asked to registrations when they sign up.
Or are you referring to the Event Espresso contact list CSV report? That also includes the contact/attendees phone numbers.
So you have not provided enough information for us to answer your questions (and actually it would help if you had exact questions). Can you provide a link to a screenshot or two showing what you want to do?

**Comment by dorian2727** [comment]
Event Registration Export to Excel – EE4

Can we customize this report? We really only need a few pieces of information. If you aren’t good with excel, it’s difficult for people to get rid of the garbage in it.
One piece of good information is “did they apply a discount code” and some of our peeps miss that sometimes because it’s WAAAAAY down on the end and not seen.
So anyway, I’d just like Amount Paid, Complete or incomplete, first name, last name, email address and promotions. That’s it.

**Comment by Pebblo** [comment]
As Mike mentioned there's really not enough information for us to help here. Opening an issue here only shows up as an issue for the entire repository so we can't tell what it is your referring to without providing that information within the opening comment.

However, I've been working on CSV exports with Dorian on the forums here:

https://eventespresso.com/topic/event-registration-export-to-excel-ee4/

I'm assuming this is basically the same question as the forums? As I've replied there already it would be best to work through this within one location so if you could please post any further questions for this in the support forum linked above we can help you there.

**Comment by dorian2727** [comment]
Ah, sorry about that... when in a topic I don't see where you can comment on that topic.
