### ISSUE TITLE
Error in Code tw_ee_password_protect_tickets.php

### ISSUE THREAD

**Issue by pheouk** [eventespresso/ee-code-snippet-library#6]
I've been struggling to get this to work, I'm finding that its showing the group tickets on the VIP page, but its also showing all the original tickets as well, with a weird number of lines on the table.  Will post back if I can figure the fix

**Comment by tn3rb** [comment]
I've looked over Tony's code in that snippet he created and it "looks" correct to me.
I would double/triple check your post and ticket IDs to ensure that they are correct.

(snippet in question: https://github.com/eventespresso/ee-code-snippet-library/blob/master/templates/tw_ee_password_protect_tickets.php)

**Comment by pheouk** [comment]
Tony has adjusted the code and issue is resolved!  Hurrah! :)
